[package]
name = "dsqprocess"
version = "0.1.0"
edition = "2021"

[dependencies]
open = "5.0"
reqwest = { version = "0.12", features = ["blocking", "json"] }
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
eframe = "0.27"

[build-dependencies]
winres = "0.1"

[[bin]]
name = "dsqprocess"
path = "src/main.rs"

[[bin]]
name = "dsqchild"
path = "src/child.rs"
